### PR TITLE
Network port creation only after bastion is ready

### LINKED ISSUE #182: Deployments with fixed_ip_v4 for bastion can lead to port reservation conflicts
Hello team,

Using the fixed_ip_v4 can lead to port reservation conflicts with bootstrap, masters, or workers.

In PowerVC you will see something like attached in the picture.

The reason for this is, that the network module can run before the bastion module and so it can pick the "reserved" IP adress from the var.tfvars.

I solved it by changed in the ocp.tf file and added some dependencies for the network module, to ensure that it isn't running before bastion has finished. I also ensured that the node module is not started before the network module.

My dependencies in the ocp.tf are looking like this now:
module "network" {
     source = "./modules/2_network"
     depends_on = [module.bastion]
<SNIP>

module "nodes" {
    source = "./module/4_nodes"
    depends_on = [module.network]
<SNIP>

module "install" {
    source = "./module/5_install"
    depends_on = [module.helpernode, module.node]
Screenshot 2021-03-12 at 08 47 43

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #182

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#pullrequestreview-613421539" title="LGTM">cs-zhang</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#pullrequestreview-613474599" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#pullrequestreview-613421539" title="LGTM">cs-zhang</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [bpradipt,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@mkumatag: new pull request created: #193

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-804673426):

>/cherry-pick release-4.7


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mkumatag** [comment]
@yussufsh it worked!

**Comment by yussufsh** [comment]
> 
> 
> @yussufsh it worked!

Can I ask to prefix the title with "Auto Cherrypick"? Only if its not too much.

**Comment by ltccci** [comment]
@yussufsh: new pull request created: #194

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-804676532):

>/cherrypick release-4.6


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ltccci** [comment]
@yussufsh: new pull request could not be created: failed to create pull request against ocp-power-automation/ocp4-upi-powervm#release-4.6 from head ltccci:cherry-pick-188-to-release-4.6: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for ltccci:cherry-pick-188-to-release-4.6."}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-804676673):

>/cherry-pick release-4.6


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ltccci** [comment]
@yussufsh: #188 failed to apply on top of branch "release-4.5":
```
Applying: Network port creation only after bastion is ready
Using index info to reconstruct a base tree...
A	modules/2_network/network.tf
A	modules/2_network/variables.tf
M	ocp.tf
Falling back to patching base and 3-way merge...
Auto-merging ocp.tf
CONFLICT (content): Merge conflict in ocp.tf
Auto-merging modules/3_network/variables.tf
Auto-merging modules/3_network/network.tf
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Network port creation only after bastion is ready
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-804678113):

>/cherrypick release-4.5


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> > @yussufsh it worked!
> 
> Can I ask to prefix the title with "Auto Cherrypick"? Only if its not too much.

I see `title = fmt.Sprintf("[%s] %s", targetBranch, title)`
from https://github.com/kubernetes/test-infra/blob/master/prow/external-plugins/cherrypicker/server.go#L467
I am not sure how to change this in the endpoint. @mkumatag Please let me know if we can we do this easily?

**Comment by mkumatag** [comment]
> > > @yussufsh it worked!
> > 
> > 
> > Can I ask to prefix the title with "Auto Cherrypick"? Only if its not too much.
> 
> I see `title = fmt.Sprintf("[%s] %s", targetBranch, title)`
> from https://github.com/kubernetes/test-infra/blob/master/prow/external-plugins/cherrypicker/server.go#L467
> I am not sure how to change this in the endpoint. @mkumatag Please let me know if we can we do this easily?

looking at the code, I don't see any other way..

**Pull request merged**
