### PR TITLE
Change module deependencies to include data sources

### LINKED ISSUE #131: Required fields not set for nodes.ft (using master and TF13)
When trying to deploy v4.6 using master branch and TF13, nodes.tf fails.

Output from apply:
module.bastion.data.openstack_compute_flavor_v2.bastion: Refreshing state...
module.network.data.openstack_networking_network_v2.network: Refreshing state...
module.network.data.openstack_networking_subnet_v2.subnet: Refreshing state...

Error: "vcpus": required field is not set
  on modules/4_nodes/nodes.tf line 46, in resource "openstack_compute_flavor_v2" "bootstrap_scg":
  46: resource "openstack_compute_flavor_v2" "bootstrap_scg" {

Error: "ram": required field is not set
  on modules/4_nodes/nodes.tf line 46, in resource "openstack_compute_flavor_v2" "bootstrap_scg":
  46: resource "openstack_compute_flavor_v2" "bootstrap_scg" {

Error: "disk": required field is not set
  on modules/4_nodes/nodes.tf line 46, in resource "openstack_compute_flavor_v2" "bootstrap_scg":
  46: resource "openstack_compute_flavor_v2" "bootstrap_scg" {

Error: "ram": required field is not set
  on modules/4_nodes/nodes.tf line 109, in resource "openstack_compute_flavor_v2" "master_scg":
 109: resource "openstack_compute_flavor_v2" "master_scg" {

Error: "disk": required field is not set
  on modules/4_nodes/nodes.tf line 109, in resource "openstack_compute_flavor_v2" "master_scg":
 109: resource "openstack_compute_flavor_v2" "master_scg" {

Error: "vcpus": required field is not set
  on modules/4_nodes/nodes.tf line 109, in resource "openstack_compute_flavor_v2" "master_scg":
 109: resource "openstack_compute_flavor_v2" "master_scg" {

Error: "vcpus": required field is not set
  on modules/4_nodes/nodes.tf line 164, in resource "openstack_compute_flavor_v2" "worker_scg":
 164: resource "openstack_compute_flavor_v2" "worker_scg" {

Error: "ram": required field is not set
  on modules/4_nodes/nodes.tf line 164, in resource "openstack_compute_flavor_v2" "worker_scg":
 164: resource "openstack_compute_flavor_v2" "worker_scg" {

Error: "disk": required field is not set
  on modules/4_nodes/nodes.tf line 164, in resource "openstack_compute_flavor_v2" "worker_scg":
 164: resource "openstack_compute_flavor_v2" "worker_scg" {

-------------
Removing line 112 from ocp.tf
module "nodes" {
    depends_on                      = [module.helpernode]        <------------- line 112 
    source                          = "./modules/4_nodes"

Allows the apply to run. 

Although the first run fails with:
image

You can re-run and cluster installs.

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #131

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#pullrequestreview-579289957" title="LGTM">Prajyot-Parab</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by pravin-dsilva — APPROVED** [review]

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#pullrequestreview-579289957" title="LGTM">Prajyot-Parab</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#pullrequestreview-579781211" title="Approved">pravin-dsilva</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#pullrequestreview-579905963" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#pullrequestreview-579289957" title="LGTM">Prajyot-Parab</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#pullrequestreview-579781211" title="Approved">pravin-dsilva</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/158#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)~~ [bpradipt,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
