### PR TITLE
Update helpernode and ocp4-playbooks tags for latest code

### LINKED ISSUE #96: Update helper node tag
Update helper node tag to get the code for setting proper permissions to named zone  files

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Fixes: #96
Signed-off-by: Prajyot Parab <prajyot.parab@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
@Prajyot-Parab Did you test this?
Specially https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/vars/main.yml#L11 is required. In my experience, this will download x86 version and fail during extraction

**Comment by yussufsh** [comment]
We either wait for https://github.com/RedHatOfficial/ocp4-helpernode/pull/140 OR provide ppc64le url in helpernode_vars.yaml.

**Comment by Prajyot-Parab** [comment]
Yes @yussufsh this would fail because of helm_source. Thanks for pointing it out.
I am fine with waiting for that PR to get merged or going ahead and doing changes related to setting `helm_source`.

**Comment by mkumatag** [comment]
reopening to run the terraform validate job

**Comment by ltccci** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [6c9a5eb](https://github.com/ocp-power-automation/ocp4-upi-powervm/commits/6c9a5eb3fa3dcd678062cfb79847cd2838396b25) Update helpernode and ocp4-playbooks tags for latest code

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/97#" title="Author self-approved">Prajyot-Parab</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yussufsh** [comment]
@Prajyot-Parab are we good to update this? Can you follow up with Christian on helpernode changes to ignore helm binary?

If that is taking more time then better add helm ppc link?

**Comment by yussufsh** [comment]
Closed by mistake. Re-opening...

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/97#" title="Author self-approved">Prajyot-Parab</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bpradipt**
You can assign the PR to them by writing `/assign @bpradipt` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervm).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@Prajyot-Parab: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-ocp4-upi-powervm-terraform-validate | 6c9a5eb3fa3dcd678062cfb79847cd2838396b25 | [link](https://prow.k8s-prow-c7f9fbfa2832409e2a3a6666e9dc52a3-0000.us-south.containers.appdomain.cloud/view/s3/prow-logs/pr-logs/pull/ocp-power-automation_ocp4-upi-powervm/97/pull-ocp4-upi-powervm-terraform-validate/1306886066493460480) | `/test pull-ocp4-upi-powervm-terraform-validate`

[Full PR test history](https://prow.k8s-prow-c7f9fbfa2832409e2a3a6666e9dc52a3-0000.us-south.containers.appdomain.cloud/pr-history?org=ocp-power-automation&repo=ocp4-upi-powervm&pr=97). [Your PR dashboard](https://prow.k8s-prow-c7f9fbfa2832409e2a3a6666e9dc52a3-0000.us-south.containers.appdomain.cloud/pr?query=is:pr+state:open+author:Prajyot-Parab).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by Prajyot-Parab** [comment]
Closing this one as no longer needed.

**Pull request closed without merging**
