### PR TITLE
Revamp install steps to run sequentially

### LINKED ISSUE #255: Unable to install dev-preview version 4.12 with nodes going into emergency shell
More information about the bug:  https://issues.redhat.com/browse/OCPBUGS-399

The reboot code when ignition fails after a timeout was removed in the latest rhcos https://github.com/coreos/fedora-coreos-config/pull/1665. The automation fails because all the pre-req services are not ready on bastion.

We need a way to run the steps sequentially.
1. Bastion
2. Network
3. Helpernode
4. Install config (ign files)
5. Bootstrap node
6. Master nodes
7. Worker nodes
8. Install
9. PostInstall
10. Upgrade

### PR DESCRIPTION
**Pull request by yussufsh**
This is required for rhcos ignition to work the first time. The rhcos node goes into emergency shell due to failed ignition when pre-req services eg: dhcp, dns, etc. is not running.

### CODE REVIEW

**Comment by yussufsh** [comment]
/cc @Prajyot-Parab
@pravin-dsilva and team already verified these changes.

**Comment by Rajalakshmi-Girish** [comment]
@yussufsh: PR is not mergeable.

<details>

The PR state is: BLOCKED

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by sudeeshjohn — APPROVED** [review]
/lgtm

**Pull request merged**
