### PR TITLE
OCTOPUS-612: Updates variables.tf to use correct nfs-client-provisioner Image

### PR DESCRIPTION
**Pull request by Chandan-Abhyankar**
OCTOPUS-612: Changes are made so that by default nfs-client-provisioner image is "registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
/meow
@Rajalakshmi-Girish

**Comment by Rajalakshmi-Girish** [comment]
> /meow @Rajalakshmi-Girish

There was an issue yesterday with triggers reaching hook.
It is fixed now.

**Pull request merged**
