### PR TITLE
Deploying cluster using non-root user

### PR DESCRIPTION
**Pull request by aishwaryabk**
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by sajauddin — APPROVED** [review]

**Comment by aishwaryabk** [comment]
@yussufsh The playbook changes are merged. Can you please review this PR? Thanks.

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
