### PR TITLE
To support Terraform v1.2.0 or above

### LINKED ISSUE #252: Support required for terraform version 1.2.0 for all branches
This is required to support centos/rhel 9 operating systems.

### PR DESCRIPTION
**Pull request by aishwaryabk**
Fixes: #252
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Review by sajauddin — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
Let me update the job config to use the latest Terraform version.

**Comment by aishwaryabk** [comment]
> Let me update the job config to use the latest Terraform version.

@yussufsh Sure. Thanks

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
