### PR TITLE
To install ansible-core on RHEL 8.6 and later

### PR DESCRIPTION
**Pull request by aishwaryabk**
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
@aishwaryabk did you try running this on CentOS stream image? both 8 and 9.
I did install a simple Centos8 stream image and I could not find `ansible` on it, `ansible-core` is available.

```
[root@bastion ~]# cat /etc/redhat-release
CentOS Stream release 8
[root@bastion ~]# yum repolist
repo id                                                                                      repo name
appstream                                                                                    CentOS Stream 8 - AppStream
baseos                                                                                       CentOS Stream 8 - BaseOS
extras                                                                                       CentOS Stream 8 - Extras
[root@bastion ~]# yum list | grep ansible
ansible-collection-microsoft-sql.noarch                 1.2.4-1.el8                                                appstream
ansible-collection-redhat-rhel_mgmt.noarch              1.1.0-2.el8                                                appstream
ansible-core.ppc64le                                    2.14.1-1.el8                                               appstream
ansible-freeipa.noarch                                  1.9.0-1.el8                                                appstream
ansible-freeipa-tests.noarch                            1.9.0-1.el8                                                appstream
ansible-pcp.noarch                                      2.2.5-1.el8                                                appstream
ansible-test.ppc64le                                    2.14.1-1.el8                                               appstream
centos-release-ansible-29.noarch                        1-2.el8                                                    extras
```

**Comment by aishwaryabk** [comment]
@yussufsh I had tried on Centos8-stream and it installed 

	ansible [core 2.13.5]
	  config file = /etc/ansible/ansible.cfg
	  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
	  ansible python module location = /usr/lib/python3.9/site-packages/ansible
	  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
	  executable location = /usr/bin/ansible
	  python version = 3.9.16 (main, Jan 17 2023, 19:02:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
	  jinja version = 3.1.2
	  libyaml = True

**Comment by aishwaryabk** [comment]
`yum install -y ansible` installs ansible [core 2.13.5]
whereas `yum install -y ansible-core` installs ansible-core 2.14.1-1.el8.
As per the code, it will install `ansible [core 2.13.5]`

**Comment by yussufsh** [comment]
/approve
As per results given by @aishwaryabk

**Review by yussufsh — APPROVED** [review]

**Pull request merged**
