### PR TITLE
Add RHCOS kernel options before installation

### PR DESCRIPTION
**Pull request by aishwaryabk**
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Review by yussufsh — CHANGES_REQUESTED** [review]
Please update the `install_playbook_tag` value to the latest commit hash, otherwise these changes won't work.

**Comment by aishwaryabk** [comment]
> Please update the `install_playbook_tag` value to the latest commit hash, otherwise these changes won't work.

Updated the playbook tag.

**Review by yussufsh — APPROVED** [review]
/lgtm

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Pull request merged**
