### PR TITLE
Update install playbook tag for ocp upgrade fix

### LINKED ISSUE #43: Fix install playbook tag for ocp upgrade
Point install playbook tag to latest tested code

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Fixes: #43 
Signed-off-by: Prajyot Parab <prajyot.parab@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
This was missed in last PR?
Can you update the commit message with reason.. "Update install playbook tag for ocp upgrade fix"

**Comment by Prajyot-Parab** [comment]
> This was missed in last PR?
> Can you update the commit message with reason.. "Update install playbook tag for ocp upgrade fix"

Yes, this was missed.
Commit message now updated.

**Comment by bpradipt** [comment]
@Prajyot-Parab please open an issue and add `Fixes` in the commit message

**Review by sudeeshjohn — DISMISSED** [review]
LGTM

**Review by yussufsh — DISMISSED** [review]

**Review by bpradipt — DISMISSED** [review]

**Review by sudeeshjohn — APPROVED** [review]

**Review by bpradipt — APPROVED** [review]
lgtm
Thanks @Prajyot-Parab

**Pull request merged**
