### PR TITLE
Fix #72: Add the possibility to specify chrony configuration for NTP

### LINKED ISSUE #72: Configure NTP servers synchronization (chrony) on CoreOS node
Create terraform variables in order to configure chrony (ntp) on coreOS node.

This is related to changes in ocp4-playbook project (commit 22f883869be8aaf9e470301a24796a20e7782d37)
issue : https://github.com/ocp-power-automation/ocp4-playbooks/issues/31
PR: https://github.com/ocp-power-automation/ocp4-playbooks/pull/34 

creation of to variable:
  `chrony_config`: true or false (default)
  `chrony_config_servers`: list of ntp server and options
  
terraform variable usage example
```
chrony_config = true
chrony_config_servers = [ {server = "0.centos.pool.ntp.org", options = "iburst"}, {server = "1.centos.pool.ntp.org", options = "iburst"} ]
```

### PR DESCRIPTION
**Pull request by schabrolles**
Create terraform variables in order to configure chrony (ntp) on coreOS node.

This is related to changes in ocp4-playbook project (commit 22f883869be8aaf9e470301a24796a20e7782d37)
issue : https://github.com/ocp-power-automation/ocp4-playbooks/issues/31
PR: https://github.com/ocp-power-automation/ocp4-playbooks/pull/34 

creation of to variable:
  `chrony_config`: true or false (default)
  `chrony_config_servers`: list of ntp server and options
  
terraform variable usage example
```
chrony_config = true
chrony_config_servers = [ {server = "0.centos.pool.ntp.org", options = "iburst"}, {server = "1.centos.pool.ntp.org", options = "iburst"} ]
```

### CODE REVIEW

**Comment by yussufsh** [comment]
@schabrolles Please update the quickstart doc with the new variables.
Also, you need to sign your commit. You can run: `git commit -m 'small message' -m 'Fixes #72' -s`. Also can use `--amend` option and force push the same commit. No need to close/recreate the PR.

**Comment by schabrolles** [comment]
@yussufsh thanks for the advice.

**Comment by yussufsh** [comment]
Time to squash all your commits into 1 with same commit message format.

**Comment by schabrolles** [comment]
How can I rebase / squash my commit without deleting the remote branch ?

**Comment by bpradipt** [comment]
> How can I rebase / squash my commit without deleting the remote branch ?

@schabrolles you can rebase and squash in your local copy and then force push it to your remote branch (`chrony_setup`)
Ref: https://www.w3docs.com/snippets/git/how-to-squash-commits-after-they-have-been-pushed.html

Let me know if there are any issues..

**Comment by schabrolles** [comment]
@bpradipt Looks ok now. thanks for the tip ;)

**Review by yussufsh — APPROVED** [review]
lgtm

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @schabrolles

**Pull request merged**
