### PR TITLE
Support PowerVC 2.0

### LINKED ISSUE #189: Add support for PowerVC 2.0

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #189

Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/approve

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by sajauddin — APPROVED** [review]
/lgtm

**Pull request merged**
