### PR TITLE
add baremetal flag in helpernode vars file

### LINKED ISSUE #273: Set baremetal flag to false explicitly in helpernode vars file template
**What is happening?**
The default value of `baremetal` flag is set to  `true` in helpernode playbook repo. This is running certain unecessary tasks, which are not required on `powervm` platform.

**Possible solution:**
Set the `baremetal` flag to `false` explicitly while generating the helpernode vars file template to fix it.

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Fixes #273

- add baremetal flag in helpernode vars file

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
/hold

@pravin-dsilva @varad-ahirwadkar Please unhold this once you are done testing it.

**Comment by yussufsh** [comment]
@Prajyot-Parab mind creating an issue?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab mind creating an issue?

Done #273

**Comment by yussufsh** [comment]
/lgtm
Feel free to unhold when you are done with testing.

**Review by yussufsh — APPROVED** [review]

**Pull request merged**
